using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PubProfileToFilezilla
{
    public class Converter
    {
        public static FileZilla3 Convert(publishData data)
        {
            var profile = data.publishProfile.First(p => p.publishMethod == PublishMethod.FTP);
            Uri uri = new Uri(profile.publishUrl);

            var zilla = new FileZilla3
            {
                Servers = new FileZilla3Servers
                {
                    Server = new FileZilla3ServersServer
                    {
                        Host = uri.Host,
                        Port = uri.Port,
                        Name = profile.profileName,
                        User = profile.userName,
                        Pass = new FileZilla3ServersServerPass
                        {
                            Value = profile.userPWD,
                            encoding = "base64",
                        },
                        Comments = @"Generated by PubProfileToFilezilla on https://github.com/jquintus/ConsoleProjects/tree/master/PubProfileToFilezilla",
                        Protocol = 0,
                        Type = 0,
                        Logontype = 1,
                        TimezoneOffset = 0,
                        PasvMode = "MODE_DEFAULT",
                        MaximumMultipleConnections = 0,
                        EncodingType = "Auto",
                        BypassProxy = 0,
                        SyncBrowsing = 0,
                    }
                }
            };

            return zilla;
        }
    }
}
